### ISSUE TITLE
Won't burn more than 1 ingot

### ISSUE THREAD

**Issue by Zack7292** [Weissmoon/Burnaces112#1]
when i put ingot, or things to burn in any furnaces, it stop when 1 finish burning.

**Comment by Weissmoon** [comment]
Are you using other mods or only Burnaces?

**Comment by Zack7292** [comment]
here a crash log: https://paste.dimdev.org/amecukekug.mccrash
the crash log don't mind but if you scroll down you'll find all the mod list because of Vanilla Fix (sorry idk why i forgot to add the link)
